export enum ProposalBadgeType {
  TEXT = 'TEXT',
  SOFTWARE_UPGRADE = 'SOFTWARE_UPGRADE',
  MSG_SOFTWARE_UPGRADE = 'MSG_SOFTWARE_UPGRADE',
  COMMUNITY_POOL_SPEND = 'COMMUNITY_POOL_SPEND',
  PARAMETER_CHANGE = 'PARAMETER_CHANGE',
}
